repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com

releases:
    - name: pod-cleaner-default
      namespace: default
      chart: ./charts/pod-cleaner
      version: 1.0
      values:
        - ./values/pod-cleaner-default.yaml

    - name: pod-cleaner-clean
      namespace: clean
      createNamespace: true
      labels:
        env: test
      chart: ./charts/pod-cleaner
      version: 1.0
      values:
        - ./values/pod-cleaner-cleaner.yaml



